Repository exercism/coffeescript, pull requests merged in 2024-03, with the labels that each got.

#285 Sort track exercises by displayed difficulty and name
  config.json
Labels: x:rep/tiny

#284 Add GHA badges to README.md
  README.md
Labels: x:rep/tiny

#283 Unpause community contributions
  .github/workflows/pause-community-contributions.yml
Labels: x:type/ci, x:rep/tiny

#287 Add allergies
  config.json
  exercises/practice/allergies/.docs/instructions.md
  exercises/practice/allergies/.meta/config.json
  exercises/practice/allergies/.meta/example.coffee
  exercises/practice/allergies/.meta/tests.toml
  exercises/practice/allergies/allergies.coffee
  exercises/practice/allergies/allergies.spec.coffee
Labels: x:module/practice-exercise, x:rep/medium

#288 Add circular-buffer
  config.json
  exercises/practice/circular-buffer/.docs/instructions.md
  exercises/practice/circular-buffer/.meta/config.json
  exercises/practice/circular-buffer/.meta/example.coffee
  exercises/practice/circular-buffer/.meta/tests.toml
  exercises/practice/circular-buffer/circular-buffer.coffee
  exercises/practice/circular-buffer/circular-buffer.spec.coffee
Labels: x:module/practice-exercise, x:rep/medium

#289 Update variable name in allergies stub
  exercises/practice/allergies/.meta/example.coffee
  exercises/practice/allergies/allergies.coffee
Labels: x:action/proofread, x:rep/tiny

#294 Update example test suite name in TESTS.md
  docs/TESTS.md
Labels: x:rep/tiny

#293 Fix test suite issues for allergies
  exercises/practice/allergies/allergies.spec.coffee
Labels: x:rep/tiny

#291 Add sieve
  config.json
  exercises/practice/sieve/.docs/instructions.md
  exercises/practice/sieve/.docs/introduction.md
  exercises/practice/sieve/.meta/config.json
  exercises/practice/sieve/.meta/example.coffee
  exercises/practice/sieve/.meta/tests.toml
  exercises/practice/sieve/sieve.coffee
  exercises/practice/sieve/sieve.spec.coffee
Labels: x:module/practice-exercise, x:rep/medium

#292 Sync tests.toml for triangle
  exercises/practice/triangle/.meta/tests.toml
Labels: x:action/sync, x:rep/tiny

#295 Add robot-simulator
  config.json
  exercises/practice/robot-simulator/.docs/instructions.md
  exercises/practice/robot-simulator/.meta/config.json
  exercises/practice/robot-simulator/.meta/example.coffee
  exercises/practice/robot-simulator/.meta/tests.toml
  exercises/practice/robot-simulator/robot-simulator.coffee
  exercises/practice/robot-simulator/robot-simulator.spec.coffee
Labels: x:module/practice-exercise, x:rep/medium

#297 Add secret handshake
  config.json
  exercises/practice/secret-handshake/.docs/instructions.md
  exercises/practice/secret-handshake/.docs/introduction.md
  exercises/practice/secret-handshake/.meta/config.json
  exercises/practice/secret-handshake/.meta/example.coffee
  exercises/practice/secret-handshake/.meta/tests.toml
  exercises/practice/secret-handshake/secret-handshake.coffee
  exercises/practice/secret-handshake/secret-handshake.spec.coffee
Labels: x:module/practice-exercise, x:rep/medium

#300 two-fer: sync
  exercises/practice/two-fer/.docs/instructions.md
  exercises/practice/two-fer/.docs/introduction.md
Labels: x:size/tiny

#299 sieve: sync
  exercises/practice/sieve/.docs/instructions.md
Labels: x:size/tiny
